### ISSUE TITLE
u32 vs u64

### ISSUE THREAD

**Issue by hatfinisher** [warner/magic-wormhole.rs#69]
What is the reason for using u32 rather than u64 here (and everywhere)?

https://github.com/warner/magic-wormhole.rs/blob/a1bc3a7f4d8c7b289bd253b9094080afcf471759/src/core/transfer.rs#L19

**Comment by warner** [comment]
laziness.. I'd be happy to change those to u64.

**Comment by warner** [comment]
Going through the PR made me think a bit more about wire-format representations of the various numbers whose types are being changed, and I figure I should be a bit more precise about what we need.

`TimerHandle` and `WSHandle` (websocket handles) are internal: they're only exposed to the IO layer. They're incremented for each new server connection we make, so they're unlikely to ever breach 8 bits, much less 32. They're used in `api.rs` and `rendezvous.rs`

The `boss::State` enums include a phase number that is incremented for each message we send to the other side. These messages go through the mailbox server, which is going to be unwilling to queue/retain more than a few dozen, so 32 bits ought to be enough.

Ping and Pong in `server_messages.rs` are for keepalive messages, which we expect to send roughly once every 60 seconds, so to break 32 bits we'd need a connection to stay up for over 8171 years.. seems unlikely :). The numbers are serialized into JSON for transmission, so as long as they remain below `2**53` we can represent them exactly, which means we're good for connections that survive up to 17 billion years, comfortably longer than the age of the universe.

The most important one is the filesize and other items in `transfer.fs`, since `u32` would limit us to 4GB files and that's *not* comfortably large. The sizes get serialized into JSON, so switching to `u64` gets us up to `2**53` bytes, which is 9 petabytes. If someone tries to send a file larger than that, the JSON representation will be inexact (it'll use floating point notation, not integer), and something will probably fail. Call me when this happens and I'll try to come up with a fix :).

Anyways, switching to `u64` doesn't cost us anything significant, so I'll land the PR.. just wanted to make some notes about the JSON representation thing while I was thinking about it.
